### ISSUE TITLE
Check "outlier" points in Mexico and Nova Scotia look in gbif

### ISSUE THREAD

**Issue by MKLau** [HarvardForest/gv-enm#30]

**Comment by anncalderon** [comment]
There were actually two in Mexico and one in Canada. One of the Mexico points doesn't have an "individual ID", but both of them have the same field id. So, I'm guessing it's the same one recorded twice, but I could be wrong.  

The one in Canada doesn't strike me as too odd since there are about three other records that occur along the same latitudes (e.g: there is one at the tip of Michigan). However, the fact that the ants would have to either cross a body of water or go through Maine and New Brunswick to get to Nova Scottia does seem a little weird, unless we consider that one record in mexico. I don't know. The other explanation I could think of is that they mean to say "44.6N, 83.64W" instead of  "44.6N, 63.64W,"
which would put the point right at the tip of Michigan as well. What do you think?

 http://www.gbif.org/occurrence/893045619 
http://www.gbif.org/occurrence/1142484687
http://www.gbif.org/occurrence/1213710800

**Comment by MKLau** [comment]
Well, I think that the observations on Mexico are very strange. If we can't track down a paper that they're associated with, they should be removed. 

I think your switched longitude coordinates makes sense, but let's say the same thing. If we can't track down a pub for it, we should leave it out.
