### ISSUE TITLE
are we at with gdistance?]

### ISSUE THREAD

**Issue by MKLau** [HarvardForest/gv-enm#50]
[Where

**Comment by anncalderon** [comment]
I am still debugging the template script and RdataTracker and ddg.run is giving us many many problems. So, I haven't had time to do any gdistance stuff. Sorry. Is it okay, if I work with the RDataTracker group to try to get the problem resolved? Otherwise, I can drop what I'm doing and work with gdistance. Let me know.

**Comment by MKLau** [comment]
Yeah, work with Moe and/or Alex to get that fixed, but don't spend more than 30 minutes on it. If you can't figure it out by then, come up and let me take a look at it.
